apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: 3d-tool

spec:
  replicas: 1

  selector:
    matchLabels: 
      app: backend
  template:
    metadata:
      labels: 
        app: backend
    spec: 
      containers:
        - name: backend
          image: praveen0031/3d-tool-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: backend-config

            - secretRef:
                name: backend-secret