apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: 3d-tool

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend
          image: praveen0031/3d-tool:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 80