apiVersion: apps/v1
kind: Deploymnt

metadata:
  name: backend
  namespace: 3d-tool

spec:
  replicas: 2

  selectors:
    matchLabels: 
      app: backend
  template:
    metadata:
      labels: 
        app: backend
    spec: 
      containers:
        - name: backend
          image: praveen0031/3d-tool-backend:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: PORT

            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: MONGO_URI

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET

            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_REFRESH_SECRET
